language: python
sudo: false
python:
  - "2.7"

env:
  - "DJANGO_VERSION=1.7"
  - "DJANGO_VERSION=1.8"
#  - "DJANGO_VERSION=master"

install:
  - cd testapp
  - python install_deps.py

script:
  - python manage.py test

after_script:
  - cd ..
  - rm django_tests
