site_name: Djangae Documentation
repo_url: https://github.com/potatolondon/djangae
pages:
    - [index.md, Home]
    - [installation.md, Installation & Deployment]
    - [unique_constraints.md, Unique Constraint Checking]
    - [db_backend.md, The Database Backend]
    - [fields.md, Djangae Model Fields]
    - [mappers.md, Map Reduce]
    - [pagination.md, Pagination]
    - [gauth.md, Gauth]
    - [uniquetool.md, Unique constraint tool]
    - [sandbox.md, Local/remote management commands]
    - [contributing.md, Contributing & Testing]
theme: readthedocs
